[build]
    command = "pip install setuptools==39.1.0 && pip install hoep --no-binary=hoep && echo 'do we get here?' && pip install -r requirements.txt && pip install mynt==0.4.0 && cd www && mynt gen -f _site"
    publish = "www/_site"
